### PR TITLE
APPSRE-3689 display cluster upgrade policy settings

### PR DESCRIPTION
**Pull request by patjlm**
I took the liberty to move the cluster ID columns at the far right in the clusters table so we gather channels and upgrade policy data close to each other. Let me know if it does not make sense.

### CODE REVIEW

**Comment by patjlm** [comment]
image

**Comment by patjlm** [comment]
image

**Review by maorfr — APPROVED** [review]
LGTM

**Comment by maorfr** [comment]
maybe put the version field next to them as well?

**Comment by patjlm** [comment]
> maybe put the version field next to them as well? you can also add the version field to the cluster page if it makes sense.

Good ideas, will do

**Comment by patjlm** [comment]
Added info in the single-cluster page:
image

And in the clusters table:
image

**Pull request merged**
