### PR TITLE
add not found page for when URL is wrong

### PR DESCRIPTION
**Pull request by SydneyDlh**
when url is wrong it routes to a not found page

### CODE REVIEW

**Comment by maorfr** [comment]
hey @SydneyDlh,

i like the idea a lot!
i'll leave the design review for @jmelis.

however, when you navigate to a url that is `.yml`, the not found page is not displayed. for example:
http://localhost:3000/services#/services/app-interface/app1.yml
instead of
http://localhost:3000/services#/services/app-interface/app.yml

**Comment by jmelis** [comment]
@SydneyDlh I agree with @maorfr, if you put a random url, the 404 page is displayed, but if you put an invalid path after the `#` it will be result in an empty page.

I was thinking about something like this:
https://gist.github.com/jmelis/1082fe9936486cfddacf482b60ca9624

But more generalized

**Comment by maorfr** [comment]
@SydneyDlh what is the status here? :)
you have added a commit but did not respond...

**Comment by SydneyDlh** [comment]
@maorfr  It got left behind as I worked on other things. I can come back to it and keep working on it

**Comment by maorfr** [comment]
thanks for all your contributions @SydneyDlh!

**Pull request merged**
