### PR TITLE
Fix links so they open in new tabs

### PR DESCRIPTION
**Pull request by SydneyDlh**
fixed all (I think) links so that they all open in new tabs.

### CODE REVIEW

**Comment by maorfr** [comment]
hey @SydneyDlh,

It seems like there are changes from previous PRs included here. this is probably because you are a few commits behind `master`.

I see that you have found the `target="_blank"` magic. that's great!
About when to use it - i think that if a user clicks on a link that leads to an external site, it should open in a new tab. if a user clicks on a link that leads to another page on visual-qontract, it should open in the same tab. does that make sense?

I hope i didn't confuse you when we spoke, i was only referring to the new link that we merged together (#9).

Thanks!

**Comment by SydneyDlh** [comment]
@maorfr  
I only changed links that go to external sites to have the target="_blank". I just noticed that only some of the grafana links open in a new tab so I decided to change all of them. I also made it so the paths that go to a .yml file on github open in a new tab as well. If you don't want all these to open in a new tab I can do just the links on the homepage. 

Also about the changes from previous PR, how do you suggest I go about dealing with that. I figured the conflict is only one line so it shouldn't be hard to resolve.

**Comment by maorfr** [comment]
hey @SydneyDlh,

regarding the _blank targets, the way you chose to do it sounds good to me, maybe i misread it.

regarding the conflicts - you should probably pull master from upstream and rebase your work on top of that.

**Comment by SydneyDlh** [comment]
@maorfr I fixed the conflicts

**Pull request merged**
